[package]
name = "raw_converter"
version = "0.1.0"
edition = "2021"

[dependencies]
tap = "1.0.1"
bitvec = "1.0.1"

[dev-dependencies]
proptest = "1.1.0"
criterion = "0.4.0"

[[bench]]
name = "bench"
harness = false